### ISSUE TITLE
MonitoringActivity uses getApplicationContext instead of getApplication

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library-reference#9]
`((BeaconReferenceApplication) this.getApplicationContext()).setMonitoringActivity(this);`

The correct way to get the application object would be:

`((BeaconReferenceApplication) this.getApplication()).setMonitoringActivity(this);`

**Comment by fWd82** [comment]
Hello
I am still getting this error:
```
FATAL EXCEPTION: main

 java.lang.RuntimeException: Unable to resume activity {MY_PACKAGE_NAME.**MonitoringActivity**}: java.lang.ClassCastException: android.app.Application cannot be cast to MY_PACKAGE_NAME.BeaconReferenceApplication
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2965)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2994)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
                                                                             at android.app.ActivityThread.access$600(ActivityThread.java:169)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:525)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:924)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to MY_PACKAGE_NAME.BeaconReferenceApplication
                                                                             at MY_PACKAGE_NAME.MonitoringActivity.onResume(MonitoringActivity.java:101)
                                                                             at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
                                                                             at android.app.Activity.performResume(Activity.java:5257)
                                                                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2952)
                                                                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2994) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                             at android.app.ActivityThread.access$600(ActivityThread.java:169) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                             at android.os.Looper.loop(Looper.java:194) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5433) 
```

**Comment by samskiter** [comment]
@fWd82 you need to cast to *your* application cast

**Comment by fWd82** [comment]
@samskiter Thank you for your comments.
Well when I cast it like:  `MyClassName.this` still it gives me errors. Do you know what to do? 
`((BeaconReferenceApplication) MyClassName.this)).setMonitoringActivity(this);`
Please how to do it. ? 
Thanks

**Comment by jprashant610** [comment]
i am facing same issue , please tell me the solution ?

**Comment by samskiter** [comment]
Don't cast to `BeaconReferenceApplication`, cast to whatever your application class is called

**Comment by Andrii-Kichmarenko** [comment]
Have the same error:
java.lang.ClassCastException: android.app.Application cannot be cast to com.andriikichmarenko.attendancecheckup.monitoring.BeaconSearcherApplication.

The answer I found sound like this: **"You can cast child class object to parent class object but you cannot do the reverse."**

**Comment by davidgyoung** [comment]
The issue is most likely that your Application class is not registered in the AndroidManifest.xml.  you need to have it like this:

<Application name="com.andriikichmarenko.attendancecheckup.monitoring.BeaconSearcherApplication"

If you need more help please open a question on Stackoverflow.com and post your code there.  Happy to support in that forum.
